### ISSUE TITLE
arrow function JSX brackets?

### ISSUE THREAD

**Issue by tizu69** [Yikes2000/prettier-plugin-merge-extras#1]
From what i can tell, this plugin formats JSX like this:

```
export default () => {
  return <div>
  // ...
```

awesome sauce! However, sometimes i use => (<...>, which it doesnt seem to remove the brackets from:

```
export default () => <div> // ...
// ^ will get turned into

export default () => (
  <div>
  // ...
```

**Comment by Yikes2000** [comment]
Thank you for reporting this issue.  It has been fixed.

Please update to version 0.7.1-extras.2 (or later) and confirm.

**Comment by tizu69** [comment]
lgtm
